In [32]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [2]:
data = pd.read_csv(r'..\top_1000_popular_movies_tmdb.csv', engine='python')
data.head()

Unnamed: 0      id                                title release_date                                             genres original_language  vote_average  vote_count  popularity                                           overview       budget                               production_companies       revenue  runtime                                  tagline
0          0  385687                               Fast X   2023-05-17                    ['Action', 'Crime', 'Thriller']           English           7.4      1347.0    8363.473  Over many missions and against impossible odds...  340000000.0  ['Universal Pictures', 'Original Film', 'One R...  6.520000e+08    142.0              The end of the road begins.
1          1  603692                 John Wick: Chapter 4   2023-03-22                    ['Action', 'Thriller', 'Crime']           English           7.9      2896.0    4210.313  With the price on his head ever increasing, Jo...   90000000.0  ['Thunder Road', '87Eleven', 'Summit Entertain...  4.317692e+08    170.0                No way back, one way out.
2          2  502356          The Super Mario Bros. Movie   2023-04-05  ['Animation', 'Family', 'Adventure', 'Fantasy'...           English           7.8      4628.0    3394.458  While working underground to fix a water main,...  100000000.0  ['Universal Pictures', 'Illumination', 'Ninten...  1.308767e+09     92.0                                      NaN
3          3  569094  Spider-Man: Across the Spider-Verse   2023-05-31  ['Action', 'Adventure', 'Animation', 'Science ...           English           8.8      1160.0    2859.047  After reuniting with Gwen Stacy, Brooklyn’s fu...  100000000.0  ['Columbia Pictures', 'Sony Pictures Animation...  3.135222e+08    140.0  It's how you wear the mask that matters
4          4  536437                             Hypnotic   2023-05-11         ['Mystery', 'Thriller', 'Science Fiction']           English           6.5       154.0    2654.854  A detective becomes entangled in a mystery inv...   70000000.0  ['Studio 8', 'Solstice Productions', 'Ingeniou...  0.000000e+00     94.0                  Control is an illusion.

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            10001 non-null  object 
 1   id                    10001 non-null  int64  
 2   title                 10001 non-null  object 
 3   release_date          9978 non-null   object 
 4   genres                10001 non-null  object 
 5   original_language     10000 non-null  object 
 6   vote_average          10000 non-null  float64
 7   vote_count            10000 non-null  float64
 8   popularity            10000 non-null  float64
 9   overview              9924 non-null   object 
 10  budget                9999 non-null   float64
 11  production_companies  9999 non-null   object 
 12  revenue               9999 non-null   float64
 13  runtime               9999 non-null   float64
 14  tagline               7383 non-null   object 
dtypes: float64(6), int6

In [4]:
data.describe()

id  vote_average    vote_count    popularity        budget       revenue      runtime
count  1.000100e+04  10000.000000  10000.000000  10000.000000  9.999000e+03  9.999000e+03  9999.000000
mean   3.001465e+05      6.319090   1558.294800     33.542340  1.993800e+07  6.084337e+07   100.809581
std    3.379901e+05      1.460605   2887.861217    126.495621  3.870582e+07  1.553073e+08    27.850165
min    0.000000e+00      0.000000      0.000000     12.297000  0.000000e+00  0.000000e+00     0.000000
25%    1.150400e+04      5.900000    143.000000     14.599000  0.000000e+00  0.000000e+00    90.000000
50%    1.184060e+05      6.600000    519.000000     18.582500  1.250000e+06  2.133452e+06   100.000000
75%    5.379150e+05      7.100000   1584.000000     28.014500  2.300000e+07  5.106230e+07   115.000000
max    1.136631e+06     10.000000  33822.000000   8363.473000  4.600000e+08  2.923706e+09   366.000000

In [5]:
data = data.iloc[:, 1:]
data.head()

id                                title release_date                                             genres original_language  vote_average  vote_count  popularity                                           overview       budget                               production_companies       revenue  runtime                                  tagline
0  385687                               Fast X   2023-05-17                    ['Action', 'Crime', 'Thriller']           English           7.4      1347.0    8363.473  Over many missions and against impossible odds...  340000000.0  ['Universal Pictures', 'Original Film', 'One R...  6.520000e+08    142.0              The end of the road begins.
1  603692                 John Wick: Chapter 4   2023-03-22                    ['Action', 'Thriller', 'Crime']           English           7.9      2896.0    4210.313  With the price on his head ever increasing, Jo...   90000000.0  ['Thunder Road', '87Eleven', 'Summit Entertain...  4.317692e+08    170.0                No way back, one way out.
2  502356          The Super Mario Bros. Movie   2023-04-05  ['Animation', 'Family', 'Adventure', 'Fantasy'...           English           7.8      4628.0    3394.458  While working underground to fix a water main,...  100000000.0  ['Universal Pictures', 'Illumination', 'Ninten...  1.308767e+09     92.0                                      NaN
3  569094  Spider-Man: Across the Spider-Verse   2023-05-31  ['Action', 'Adventure', 'Animation', 'Science ...           English           8.8      1160.0    2859.047  After reuniting with Gwen Stacy, Brooklyn’s fu...  100000000.0  ['Columbia Pictures', 'Sony Pictures Animation...  3.135222e+08    140.0  It's how you wear the mask that matters
4  536437                             Hypnotic   2023-05-11         ['Mystery', 'Thriller', 'Science Fiction']           English           6.5       154.0    2654.854  A detective becomes entangled in a mystery inv...   70000000.0  ['Studio 8', 'Solstice Productions', 'Ingeniou...  0.000000e+00     94.0                  Control is an illusion.

In [6]:
data.columns

Index(['id', 'title', 'release_date', 'genres', 'original_language', 'vote_average', 'vote_count', 'popularity', 'overview', 'budget', 'production_companies', 'revenue', 'runtime', 'tagline'], dtype='object')

In [7]:
movies = data[['id', 'title', 'genres', 'overview']]
movies.head()

id                                title                                             genres                                           overview
0  385687                               Fast X                    ['Action', 'Crime', 'Thriller']  Over many missions and against impossible odds...
1  603692                 John Wick: Chapter 4                    ['Action', 'Thriller', 'Crime']  With the price on his head ever increasing, Jo...
2  502356          The Super Mario Bros. Movie  ['Animation', 'Family', 'Adventure', 'Fantasy'...  While working underground to fix a water main,...
3  569094  Spider-Man: Across the Spider-Verse  ['Action', 'Adventure', 'Animation', 'Science ...  After reuniting with Gwen Stacy, Brooklyn’s fu...
4  536437                             Hypnotic         ['Mystery', 'Thriller', 'Science Fiction']  A detective becomes entangled in a mystery inv...

In [8]:
eval(movies.genres[0])

['Action', 'Crime', 'Thriller']

In [9]:
movies['genres'] = movies['genres'].apply(lambda x: x.replace('[', '').replace(']', '').replace("'", ''))

movies['tags'] = movies['overview'] + movies['genres']
movies = movies.drop(columns=['overview', 'genres'])
movies.head()

C:\Users\Anar\AppData\Local\Temp\ipykernel_2724\1735695304.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(lambda x: x.replace('[', '').replace(']', '').replace("'", ''))
C:\Users\Anar\AppData\Local\Temp\ipykernel_2724\1735695304.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genres']


id                                title                                               tags
0  385687                               Fast X  Over many missions and against impossible odds...
1  603692                 John Wick: Chapter 4  With the price on his head ever increasing, Jo...
2  502356          The Super Mario Bros. Movie  While working underground to fix a water main,...
3  569094  Spider-Man: Across the Spider-Verse  After reuniting with Gwen Stacy, Brooklyn’s fu...
4  536437                             Hypnotic  A detective becomes entangled in a mystery inv...

In [10]:
cv = CountVectorizer(max_features=10000,
                     stop_words='english')

vector = cv.fit_transform(movies['tags'].values.astype(str)).toarray()

In [11]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
vector[vector != 0][:20]

array([1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [13]:
sim = cosine_similarity(vector)
sim[:10]

C:\Users\Anar\PycharmProjects\scientificProject\env\lib\site-packages\sklearn\utils\extmath.py:189: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b


array([[1.        , 0.12555296, 0.05884899, ..., 0.04688072, 0.        ,
        0.        ],
       [0.12555296, 1.        , 0.03232541, ..., 0.05150262, 0.        ,
        0.        ],
       [0.05884899, 0.03232541, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.05039526, 0.        , 0.10379986, ..., 0.        , 0.0745356 ,
        0.05679618],
       [0.10350983, 0.0379049 , 0.07106691, ..., 0.1132277 , 0.        ,
        0.07777138],
       [0.11065667, 0.08104409, 0.03798686, ..., 0.12104551, 0.        ,
        0.0277137 ]])

In [16]:
sim[2, :5]

array([0.05884899, 0.03232541, 1.        , 0.10379986, 0.        ])

In [80]:
list_of_sim = list(enumerate(sim[2]))
list_of_sim.sort(reverse=True, key=lambda e:e[1])

recommended_5 = [tuple([movies.iloc[tpl[0]].title, *tpl]) for tpl in list_of_sim[1:6]]
recommended_5

[('Onward', 1997, 0.3892494720807615),
 ('The Ice Age Adventures of Buck Wild', 289, 0.32667930388828254),
 ('Super Mario Bros.', 1728, 0.32667930388828254),
 ('Super Mario Brothers: Great Mission to Rescue Princess Peach',
  4724,
  0.32566947363946486),
 ('The Dark Crystal', 7949, 0.2969078476100822)]

In [94]:
cv_title = CountVectorizer(max_features=10000,
                           stop_words='english')

vector_title = cv_title.fit_transform(movies['title'].values.astype(str)).toarray()

tr = cv_title.transform([movies['title'][1]]).toarray()
tr

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [95]:
sim_title = cosine_similarity(vector_title)
sim_title[:5]

C:\Users\Anar\PycharmProjects\scientificProject\env\lib\site-packages\sklearn\utils\extmath.py:189: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [96]:
sim[2]

array([0.05884899, 0.03232541, 1.        , ..., 0.        , 0.        ,
       0.        ])

In [98]:
movies.iloc[2]

id                                                  502356
title                          The Super Mario Bros. Movie
tags     While working underground to fix a water main,...
Name: 2, dtype: object

### Bot part

In [25]:
import spacy
nlp = spacy.load('en_core_web_lg')

In [31]:
user_inp = nlp(input())
title = nlp(movies['title'][1])

title.similarity(user_inp)

0.629543839295777

In [39]:
titles =  movies['title'].apply(lambda x: nlp(x)).to_numpy()

CPU times: total: 32 s
Wall time: 49.1 s


In [79]:
%%time

user_inp = nlp(input())

def select_title(user_inp):
    similar_names = [(title,title.similarity(user_inp)) for title in titles]
    similar_names.sort(reverse=True, key=lambda e:e[1])

    return similar_names[:5]

select_title(user_inp)



CPU times: total: 46.9 ms
Wall time: 8.22 s


<timed exec>:4: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.


[(John Wick: Chapter 4, 0.7793602379375979),
 (Stuart Little 2, 0.7675122202342565),
 (Emmanuelle 4, 0.7669385820530642),
 (John Wick: Chapter 5, 0.765838400738984),
 (Schoolmistress 4, 0.7589702414646425)]

In [82]:
def similar_movies(mov_title):
    movie_index = movies[movies['title'] == mov_title].index
    list_of_sim = list(enumerate(sim[movie_index[0]]))
    list_of_sim.sort(reverse=True, key=lambda e:e[1])

    recommended_5 = [(movies.iloc[tpl[0]].title, *tpl) for tpl in list_of_sim[1:10]]
    return recommended_5

similar_movies('John Wick: Chapter 4')

[('John Wick: Chapter 3 - Parabellum', 167, 0.4060103533960191),
 ('John Wick: Chapter 5', 2738, 0.33593550657351257),
 ('Now You See Me 2', 2013, 0.2836543144655877),
 ('John Wick', 404, 0.2799462554779272),
 ('John Wick: Chapter 2', 164, 0.27586206896551724),
 ('Fantastic Four: Rise of the Silver Surfer', 1807, 0.2456518422202587),
 ('The Gray Man', 638, 0.23973165074269204),
 ('Nameless Gangster', 6905, 0.23973165074269204),
 ('The Equalizer 3', 992, 0.2373222262672836)]

In [11]:
similar_10 = [('John Wick: Chapter 3 - Parabellum', 167, 0.4060103533960191),
 ('John Wick: Chapter 5', 2738, 0.33593550657351257),
 ('Now You See Me 2', 2013, 0.2836543144655877),
 ('John Wick', 404, 0.2799462554779272),
 ('John Wick: Chapter 2', 164, 0.27586206896551724),
 ('Fantastic Four: Rise of the Silver Surfer', 1807, 0.2456518422202587),
 ('The Gray Man', 638, 0.23973165074269204),
 ('Nameless Gangster', 6905, 0.23973165074269204),
 ('The Equalizer 3', 992, 0.2373222262672836)]

In [25]:
response = ''
for i, tpl in enumerate(similar_10, 2):
    if tpl[2] > 0.4:
        response += f'{tpl[0]}  --> Score: {round(tpl[2] * 100, 1)}% ⬆️️\n\n'
    else:
        response += f'{tpl[0]}  --> Score: {round(tpl[2] * 100, 1)}% ↗️️\n\n'
print('<b>🤖 Here are 10 movies that are similar in genre or theme🤖</b> \n\n\n' + response)


<b>🤖 Here are 10 movies that are similar in genre or theme🤖</b> 


John Wick: Chapter 3 - Parabellum  --> Score: 40.6% ⬆️️

John Wick: Chapter 5  --> Score: 33.6% ↗️️

Now You See Me 2  --> Score: 28.4% ↗️️

John Wick  --> Score: 28.0% ↗️️

John Wick: Chapter 2  --> Score: 27.6% ↗️️

Fantastic Four: Rise of the Silver Surfer  --> Score: 24.6% ↗️️

The Gray Man  --> Score: 24.0% ↗️️

Nameless Gangster  --> Score: 24.0% ↗️️

The Equalizer 3  --> Score: 23.7% ↗️️


